using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class PlayerContoller : MonoBehaviour
{
    [SerializeField] AttachmentObj _attachClass;
    List<GameObject> _cameraPointList;
    Image _crossHier;
    float _mouseWheel;
    bool _shotOK = true;
    int _listNumber = 0;
    GameObject _hold;


    private void Start()
    {
        _cameraPointList = _attachClass.GetCameraPoint;
        _crossHier = _attachClass.GetCrossHire;
        _cameraPointList[0].SetActive(true);
        _hold = _cameraPointList[0];
        
    }

    private void Update()
    {
        Cursor.visible = false;
        //inGameï¿½ï¿½falseï¿½Ìï¿½ï¿½ï¿½crosshairï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        if(!GameManager.Instance.IsGame)
        {
            _crossHier.gameObject.SetActive(false);
        }

        //Rayï¿½ï¿½ï¿½Î‚ï¿½
        Ray _ray = Camera.main.ScreenPointToRay(_crossHier.rectTransform.position);

        //Rayï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½É‘ÎÛ‚ï¿½Objï¿½ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½ï¿½ifï¿½Ì’ï¿½ï¿½É“ï¿½ï¿½ï¿½
        if (Physics.Raycast(_ray, out RaycastHit _hit))
        {
            //ï¿½ÎÛ‚ï¿½ActiveBaseï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Aï¿½Qï¿½[ï¿½ï¿½Playï¿½ï¿½ï¿½Éï¿½ï¿½Nï¿½ï¿½ï¿½bï¿½Nï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
            if (_hit.collider.gameObject.TryGetComponent<ActiveBase>(out var _active)
                && Input.GetButton("Fire1") && _shotOK)
            {
                //Activeï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚Ñoï¿½ï¿½
                _active.Active();
            }

        }

        //ï¿½}ï¿½Eï¿½Xï¿½zï¿½Cï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½Éï¿½ï¿½s
        _mouseWheel = Input.GetAxis("Mouse ScrollWheel");

        //ï¿½}ï¿½Eï¿½Xï¿½zï¿½Cï¿½[ï¿½ï¿½ï¿½ğ“®‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É‚ï¿½é•ªï¿½ï¿½
        if (_mouseWheel > 0)
        {
            _listNumber++;
            //ï¿½×Ú‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ÉØ‚ï¿½Ö‚ï¿½ï¿½ï¿½
            if (_listNumber >= _cameraPointList.Count)
            {
                _listNumber = 0;
                _hold.SetActive(false);
                _cameraPointList[_listNumber].SetActive(true);
                _hold = _cameraPointList[_listNumber];
            }
            else if (_listNumber < _cameraPointList.Count)
            {
                _hold.SetActive(false);
                _cameraPointList[_listNumber].SetActive(true);
                _hold = _cameraPointList[_listNumber];
            }

        }
        else if (_mouseWheel < 0)
        {
            _listNumber--;

            //ï¿½×Ú‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ÉØ‚ï¿½Ö‚ï¿½ï¿½ï¿½
            if (_listNumber < 0)
            {
                _listNumber = _cameraPointList.Count - 1;
                _hold.SetActive(false);
                _cameraPointList[_listNumber].SetActive(true);
                _hold = _cameraPointList[_listNumber];
            }
            else if (_listNumber >= 0)
            {
                _hold.SetActive(false);
                _cameraPointList[_listNumber].SetActive(true);
                _hold = _cameraPointList[_listNumber];
            }
        }
    }

    [System.Serializable]
    class AttachmentObj
    {
        [Header("CameraPoint")]
        [SerializeField] List<GameObject> _cameraPoint = new();
        public List<GameObject> GetCameraPoint => _cameraPoint;

        [Header("CrossHire")]
        [SerializeField] Image _crossHire;
        public Image GetCrossHire
        {
            set { _crossHire = value; }
            get { return _crossHire; }
        }
    }
}